/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        serif: ['var(--font-display)', 'ui-serif', 'Georgia', 'serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        pt: {
          ink: '#1c1917',
          body: '#57514b',
          soft: '#4a443e',
          muted: '#6f6a65',
          faint: '#8a827a',
          subtle: '#9c968f',
          ghost: '#a8a19a',
          whisper: '#b3aca4',
          dashed: '#ccc5bd',
          line: '#e7e3df',
          lineStrong: '#ddd8d2',
          surface: '#ffffff',
          surfaceSoft: '#faf9f7',
          shell: '#f4f2ef',
          canvas: '#eceae6',
          accent: '#7c2d5e',
          accentDark: '#5c1f45',
          accentSoft: '#f2e7ee',
          accentBorder: '#c9a8bc',
          accentText: '#a06484',
          good: '#3d6b52',
          goodSoft: '#e8f0ea',
          warn: '#856531',
          warnSoft: '#f4ede0',
          info: '#3f5a78',
          infoSoft: '#e9eef4',
          danger: '#8a5055',
          dangerSoft: '#f4eaea',
          overdue: '#8a3f47',
          tan: '#e6dcd2',
          tanText: '#6b5a4e',
          sage: '#dfe4e0',
          sageText: '#4f5b52',
          sky: '#eaf3f8',
          skyText: '#2f6182',
          violet: '#f0ecf6',
          violetText: '#5b4a80',
        },
      },
    },
  },
  plugins: [],
}
